---
- hosts: dsv
  vars_files:
    - ../../config/{{type}}.yaml

  tasks:
    # install deps
  - name: Installing git, npm and nodejs
    apt: name={{item}} state=latest
    with_items:
    - git
    - nodejs
    - npm
    sudo: yes

    # add dsv user
  - name: Adding user dsv
    user: name=dsv shell=/bin/bash
    sudo: yes

    # install dsv
  - name: Pulling dsv repo
    git: repo={{dsv_repo}} dest=/home/dsv/dsv/ force=yes version={{dsv_version}}
    become: yes
    become_user: dsv
  - name: NPM Install in dsv
    npm: path=/home/dsv/dsv/
    become: yes
    become_user: dsv
  - name: Setting dsv Settings
    template: src=config/{{item}} dest=/home/dsv/dsv/config/{{item}}
    become: yes
    become_user: dsv
    with_items:
    - dscGateway.js
    - network.js

    # create dsv service and start
  - name: Seting up dsv systemd service
    template: src=other/dsv.service dest=/etc/systemd/system/dsv.service owner=root group=root
    sudo: yes
  - name: Reload systemd
    command: systemctl daemon-reload
    sudo: yes
  - name: Restarting dsv systemd service
    service: name=dsv state=restarted enabled=yes
    sudo: yes
