---
- hosts: dsv
  remote_user: diana
  vars_files:
    - ../../config/{{type}}.yaml

  tasks:
  - name: Installing git, npm and nodejs
    apt: name={{item}} state=latest
    with_items:
    - git
    - nodejs
    - npm
    sudo: yes

  - name: Adding user dsv
    user: name=dsv shell=/bin/bash
    sudo: yes

  - name: Pulling dsv repo
    git: repo={{dsv_repo}} dest=/home/dsv/dsv/ force=yes version={{dsv_version}}
    become: yes
    become_user: dsv
  - name: NPM Install in dsv
    npm: path=/home/dsv/dsv/
    become: yes
    become_user: dsv

  - name: Setting dscGateway Settings
    template: src=config/dscGateway.js dest=/home/dsv/dsv/config/dscGateway.js owner=dsv group=dsv
    sudo: yes
  - name: Setting network Settings
    template: src=config/network.js dest=/home/dsv/dsv/config/network.js owner=dsv group=dsv
    sudo: yes

  - name: Seting up dsv systemd service
    template: src=other/dsv.service dest=/etc/systemd/system/dsv.service owner=root group=root
    sudo: yes
  - name: Reload systemd
    command: systemctl daemon-reload
    sudo: yes
  - name: Restarting dsv systemd service
    service: name=dsv state=restarted enabled=yes
    sudo: yes
