---
- hosts: "dsc"
  vars_files:
  - config/main.yaml
  - config/network.yaml
  - config/dsc.yaml
  remote_user: "{{remote_user}}"
  vars:
    gui_url: "127.0.0.1:{{dsc_port}}/?key={{dsc_key}}"
  roles:
    - gui
    - tools
    - ntp
    - grub
    - aptcache
    - dsc
