---
- hosts: "dsv"
  vars_files:
  - config/main.yaml
  - config/network.yaml
  - config/dsv.yaml
  - config/dsc-gateway.yaml
  remote_user: "{{remote_user}}"
  vars:
    gui_url: "127.0.0.1:{{dsv_port}}"
    dsv_dsc_gateway_url: "{{ip}}:{{dsc_gateway_port}}"
  roles:
    - gui
    - tools
    - ntp
    - grub
    - aptcache
    - dsv
    - dsc-gateway
