---
- hosts: dsc
  remote_user: diana
  vars_files:
    - ../../config/{{type}}.yaml

  tasks:
  - name: Install git, npm, nodejs, mysql
    apt: name={{item}} state=latest
    with_items:
    - git
    - nodejs
    - npm
    - mysql-server
    - python-mysqldb
    sudo: yes

  - name: Adding user dsc
    user: name=dsc shell=/bin/bash
    sudo: yes
  - name: Adding user dsc to dialout group...
    user: name=dsc state=present groups="dialout"
    sudo: yes

  - name: Pulling dsc repo
    git: repo={{dsc_repo}} dest=/home/dsc/dsc/ force=yes version={{dsc_version}}
    become: yes
    become_user: dsc
  - name: NPM Install in dsc
    npm: path=/home/dsc/dsc/
    become: yes
    become_user: dsc
  - name: Make haering lib
    command: bash -c "cd /home/dsc/dsc/lib/Haering/ && ./buildAPI.sh"
    become: yes
    become_user: dsc

  - name: Set up dsc stand config
    template: src=config/line.js dest=/home/dsc/dsc/config/line.js
    become: yes
    become_user: dsc
  - name: Set up dsc auth config
    template: src=config/auth.js dest=/home/dsc/dsc/config/auth.js
    become: yes
    become_user: dsc
  - name: Set up dsc database config
    template: src=config/database.js dest=/home/dsc/dsc/config/database.js
    become: yes
    become_user: dsc


  - name: Configure mysql root
    mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
    with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
    sudo: yes
  - name: copy .my.cnf file with root password credentials
    template: src=mysql/my.cnf dest=/root/.my.cnf owner=root group=root mode=0600
    sudo: yes
  - mysql_db: name=mysql state=import target=/home/dsc/dsc/install/database.sql
    sudo: yes

  - name: copy dsc setPassword SQL file
    template: src=mysql/setPassword.sql dest=/tmp/setPassword.sql owner=root group=root mode=0600
    sudo: yes
  - mysql_db: name=mysql state=import target=/tmp/setPassword.sql
    sudo: yes

  - name: Copy MySQL cnf
    template: src=mysql/my.server.cnf dest=/etc/mysql/my.cnf owner=root group=root mode=0600
    sudo: yes
  - name: Restart the MySQL service
    action: service name=mysql state=restarted enabled=true
    sudo: yes


  - name: Set up dsc systemd service
    template: src=other/dsc.service dest=/etc/systemd/system/dsc.service owner=root group=root
    sudo: yes
  - name: Reload systemd
    command: systemctl daemon-reload
    sudo: yes
  - name: Restart & enable dsc systemd service
    service: name=dsc state=restarted enabled=yes
    sudo: yes
