---
- hosts: all
  remote_user: diana
  vars_files:
    - ../../config/{{type}}.yaml

  tasks:
    # install deps
  - name: Installing htop, tmux, ntp
    apt: name={{item}} state=latest
    with_items:
    - htop
    - tmux
    - ntp
    - openssl
    sudo: yes

    # configure ntp
  - name: Seting up ntp config
    template: src=etc/ntp.conf dest=/etc/ntp.conf
    sudo: yes
  - name: Stoping ntp systemd service
    service: name=ntp state=stopped enabled=yes
    sudo: yes
  - name: Syncing time
    command: bash -c "ntpd -g"
    sudo: yes
  - name: Write time to hardware
    command: bash -c "hwclock --systohc"
    sudo: yes
  - name: Starting ntp systemd service
    service: name=ntp state=started enabled=yes
    sudo: yes

    # configure grub without waiting
  - name: Seting up GRUB config
    template: src=etc/grub dest=/etc/default/grub
    sudo: yes
  - name: Update GRUB
    command: update-grub
    sudo: yes
