---
- hosts: all
  remote_user: diana
  vars:
    networking_gateway: 10.13.0.1
    networking_netmask: 255.255.255.0
    networking_nameservers: 10.13.0.1

  tasks:
  - name: Seting network config
    template: src=etc/interfaces dest=/etc/network/interfaces owner=root group=root
    sudo: yes

  - name: Restarting network
    command: bash -c "ifdown eth0 && ifup eth0"
    sudo: yes

  - name: Updateing apt cache
    apt: update_cache=yes
    sudo: yes
