---
- hosts: all
  vars_files:
    - ../../config/{{type}}.yaml

  tasks:
    # install deps
  - name: Installing dwm, suckless-tools, xinit, surf, etc
    apt: name={{item}} state=latest
    with_items:
    - dwm
    - git
    - suckless-tools
    - xinit
    - surf
    - build-essential
    - libx11-dev
    - libxinerama-dev
    - sharutils
    - unclutter
    - ttf-liberation
    sudo: yes

    # build dwm display manager
  - name: Pulling dwm repo
    git: repo={{gui_dwm_repo}} dest=/tmp/dwm/ force=yes
    sudo: yes
  - name: Make dwm
    command: bash -c "cd /tmp/dwm/ && make clean && make && make install"
    sudo: yes

    # add user gui and enable autlogin/ start
  - name: Adding user gui
    user: name=gui shell=/bin/bash
    sudo: yes
  - name: Seting up Autologin for gui on tty1 (1)
    file: path=/etc/systemd/system/getty@tty1.service.d state=directory mode=0755
    sudo: yes
  - name: Seting up Autologin for gui on tty1 (2)
    template: src=other/autologin.conf dest=/etc/systemd/system/getty@tty1.service.d/autologin.conf
    sudo: yes
  - name: Seting .xinitrc and .bash_profile for gui
    template: src=gui/xinitrc dest=/home/gui/{{item}} mode=0700
    become: yes
    become_user: gui
    with_items:
    - ".xinitrc"
    - ".bash_profile"
