---
- hosts: dsc
  remote_user: diana
  tasks:

  - name: Install git
    apt: pkg=git state=latest
    sudo: yes
  - name: Install npm
    apt: pkg=npm state=latest
    sudo: yes
  - name: Install nodejs
    apt: pkg=nodejs state=latest
    sudo: yes

  - name: Pull dsc repo
    git: repo=https://github.com/janniklorenz/Shooting-Client.git dest=/home/diana/dsc/
  - name: NPM Install in dsc
    npm: path=/home/diana/dsc/  

  - name: Set up dsc systemd service
    template: src=dsc.service dest=/etc/systemd/system/dsc.service owner=root group=root
    sudo: yes
  - name: Restart dsc systemd service
    service: name=dsc state=restarted enabled=yes
    sudo: yes
