---
- hosts: dsc
  remote_user: diana

  tasks:
  - name: Install git, npm and nodejs
    apt: name={{item}} state=latest
    with_items:
    - git
    - nodejs
    - npm
    sudo: yes
  - name: Add User to dialout group
    user: name=diana state=present groups="dialout"
    sudo: yes

  - name: Pull dsc repo
    git: repo=http://DSM/DigitalShooting/DSC.git dest=/home/diana/dsc/ force=yes
  - name: NPM Install in dsc
    npm: path=/home/diana/dsc/
  - name: Make haering lib
    command: bash -c "cd /home/diana/dsc && ./buildAPI.sh"

  - name: Set up dsc stand config
    template: src=stand.js dest=/home/diana/dsc/config/stand.js
  - name: Set up dsc interface config
    template: src=interface.js dest=/home/diana/dsc/config/interface.js

  - name: Set up dsc systemd service
    template: src=dsc.service dest=/etc/systemd/system/dsc.service owner=root group=root
    sudo: yes
  - name: Restart dsc systemd service
    service: name=dsc state=restarted enabled=yes
    sudo: yes
