---
dsc_repo: https://github.com/DigitalShooting/DSC.git
dsc_version: v1.3
dsc_key: jvKLefsjw
dsc_verein: SV Diana Dettingen
dsc_port: 3000

gui_dwm_repo: https://github.com/DigitalShooting/dwm.git
gui_url: 127.0.0.1:{{dsc_port}}/?key={{dsc_key}}

networking_gateway: 10.13.0.1
networking_netmask: 255.255.255.0
networking_nameservers: 10.13.0.1

tools_ntp_server: 10.0.0.10
