---

# main dsc repo url
dsc_repo: "https://git.janniklorenz.de/diana/DSC.git"

# git tag or branch to use
dsc_version: "master"

# static auth key
dsc_key: "346ef77b4a203ab1a457d9770acdba"

# verein label (Print)
dsc_verein: "SV Diana Dettingen"

# stand number (overwrite in ansible host file)
# dsc_stand: "0"

# port for dsc server
dsc_port: "3000"



# ##### MySQL #####
#
# # mysql root password (change before first run)
# mysql_root_password: "ek-pynd-oct-id-goc-v"
#
# # mysql dsc user password (wildcard login allowed)
# mysql_dsc_password: "a69a6f90cda4e19c36a49aa4c3a4f84c70513547f108e5aeaf2ba7a3b23e23eb"
