---

##### Main #####

# remote user to connect with (sudo without password required)
remote_user: "diana"

# base url for all git repos
remote_git_url: "https://github.com/DigitalShooting/"




##### DSV #####

# main dsv repo url
dsv_repo: https://github.com/DigitalShooting/DSV.git

# git tag or branch to use
dsv_version: v1.1

# port for dsv server
dsv_port: 3001




##### DSC-Gateway #####

# main dsc-gateway repo url
dsc_gateway_repo: https://github.com/DigitalShooting/DSC-Gateway.git

# git tag or branch to use
dsc_gateway_version: master

# port for dsc-gateway server
dsc_gateway_port: 4000




##### GUI #####

gui_dwm_repo: https://github.com/DigitalShooting/dwm.git
gui_url: 127.0.0.1:{{dsv_port}}




##### Network #####

# ipv4 address (overwrite in ansible host file)
networking_ip: 10.1.0.200

# ipv4 gateway, netmask and dns
networking_gateway: "10.1.0.1"
networking_netmask: "255.255.255.0"
networking_nameservers: "10.1.0.1"

# ntp server
tools_ntp_server: "10.0.0.10"
